delete from Choices
delete from Instructor_Course
delete from Student_Course
delete from Student_Exam
delete from Question
delete from Topic
delete from Exam_Question
delete from Exam
delete from Instructor
delete from Student
delete from Department
delete from Course